### ISSUE TITLE
Switching from mcollectived to choria-server; nats server cert invalid

### ISSUE THREAD

**Issue by nburg** [choria-io/puppet-choria#105]
I get this error on my choria server after switching from the puppetagent rpm pacakge provided mcollectived to the choria package provided through the choria puppetforge module:
{"component":"server","connection":"a.example.com","identity":"a.example.com","level":"warning","msg":"Initial connection to the NATS broker cluster failed: x509: certificate is valid for choria.example.com, choriavip.example.com, not puppet","time":"2019-01-15T12:08:28-06:00"}
In the configs for choria-server I have the middleware set to choriavip.example.com. This was working with mcollectived. choriavip.example.com is a load balancer in front of the nats server, choria.example.com. choria.example.com's has a SAN cert including choriavip.example.com

**Comment by nburg** [comment]
Choria package is choria-0.9.0-1.el7.x86_64

**Comment by ripienaar** [comment]
I suspect whats happening is that your configuration to configure custom middleware names have gotten lost - and i think this is my fault for some glaring omission in the docs.

Can you tell me how you're configuring the middleware to connect to, here it's trying to connect to `puppet` which is the default when not configured.

**Comment by nburg** [comment]
I have
```
mcollective_choria::config:
  middleware_hosts: choriavip.example.com:4222
```
set in hiera which looks like it gives me
`middleware_hosts = choriavip.example.com:4222`
in /etc/puppetlabs/mcollective/plugin.d/choria.cfg

**Comment by ripienaar** [comment]
OK, so this is what I thought, I need to update the docs and make clearer how to move config or try to do it transparently as it's 2 seperate modules :( 

For now though, try this:

```yaml
choria::server_config:
  plugin.choria.middleware_hosts: choriavip.example.com:4222
```

This should configure it again to use the right hostname for the middleware and your certs should line up
This should correctly configure the choria bits with your desired settings.

**Comment by nburg** [comment]
Thanks, that took care of that error message. Now I'm getting
`{"component":"server","identity":"a.uchicago.edu","level":"error","msg":"Could not decode incoming request: SecureRequest message created from the Transport Message did not pass security validation","time":"2019-01-16T06:33:08-06:00"`

**Comment by nburg** [comment]
Thanks, that took care of that error message. Now I'm getting
`{"component":"server","identity":"a.example.com","level":"error","msg":"Could not decode incoming request: SecureRequest message created from the Transport Message did not pass security validation","time":"2019-01-16T06:33:08-06:00"`

**Comment by ripienaar** [comment]
is that all it logs, mind kicking it into debug mode?

Is this perhaps a puppet ruby 5 client talking to a new server?

**Comment by nburg** [comment]
debug log: [](https://pastebin.com/HeeRvSxa)
a.example.com is running puppet agent 6.1 and choria-0.9.0-1.el7.x86_64
choriavip.example.com has puppet 5.5.8 installed and choria-0.9.0-1.el7.x86_64

**Comment by ripienaar** [comment]
OK, in a mix 5 and 6 environment you need to do the things here https://choria.io/docs/configuration/choria_server/ specifically:

```
mcollective_choria::config:
  security.serializer: "json"
```

**Comment by nburg** [comment]
I have that set, but if you think it is a 5 and 6 issue I can go ahead and upgrade puppet agent on my broker.

**Comment by ripienaar** [comment]
I will keep this open to track the doc issue
