### ISSUE TITLE
Add Fedora support

### ISSUE THREAD

**Issue by vchepkov** [choria-io/puppet-choria#108]
Please consider adding Fedora support.

**Comment by vchepkov** [comment]
RHEL7 package works on Fedora 29, I just had to install it manually, since overriding default repo url is not an option at the moment.

**Comment by ripienaar** [comment]
The difficulty for me at least is that fedora release life cycles is pretty short, like for RHEL, Ubuntu and Debian I target the LTS and its managable, but Fedora moves very fast meaning a lot of churn, I can write guidance on how to add it but not sure I can fully support it

**Comment by vchepkov** [comment]
Considering package from EL7 works, maybe make repo URL configurable?
I can hack a workaround with `choria::repo::ensure: absent` and my own repo definition, but having it as a module option would be preferred. One would need to do a hack for RHEL8 beta too, I would imagine, for the time being?
