### ISSUE TITLE
Disable repo_gpgcheck for choria yum repos

### ISSUE THREAD

**Issue by ExalDraen** [choria-io/puppet-choria#111]
Per the discussion in #107 there is an issue when using mirrors for the packagecloud yum repos: due to the way the GPG signatures for repo metadata (`repomd.xml.asc`) are stored, they are not copied across when creating a mirror for packagecloud using the instructions provided (`reposync` followed by `createrepo`). 

I contacted packagecloud and they confirmed that this is the case.

The only workaround at the moment is to use one's own GPG infrastructure to generate metadata and metadata signatures. This is of course doable but raises the barrier for entry for people who just want to use an internal repo that they trust (and thus don't need to have GPG signatures for). 

As a first iteration, I'm suggesting we disable the repo check for yum repos. I will send a PR to that effect.

**Comment by ripienaar** [comment]
thank you!
