### ISSUE TITLE
Ensure the Debian repository is added before the choria package is installed

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-choria#113]
The module does not enforce the choria repository to be managed before the choria package.  When adding this module to a node, the first run may fail because Puppet attempts to install the choria package  which is not yet available.

**Comment by khaefeli** [comment]
This doesn't help here: #80 
I had to workaround it with the following code in the `init.pp`

`
...
{
    class{"choria::repo":
      nightly => $nightly_repo,
      ensure  => $ensure,
      before  => Class["choria::install"],
      notify => Exec['choria_repo_force']
    } ->

   exec { 'choria_repo_force':
      command     => "/bin/echo 'forcing apt update for choria'",
      refreshonly => true,
      logoutput   => true,
      subscribe   => Exec['apt_update'],
    } 


  -> class{"choria::install": }
...
`

**Comment by smortex** [comment]
Oh!  I believe you are right: apt needs to be *updated* before attempting to *install* anything when a new source is added.

I believe we can avoid the `exec` resource: the following dependency should do the trick:

```pupppet
Class['apt::update'] ~> Package[$choria::package_name]
```

@khaefeli, can you give it a try and confirm that it fix your problem?

**Comment by khaefeli** [comment]
@smortex yes, adding it to the `init.pp` helped. 
I think I tried this as well, but something seems to be strange on my test system: #80

**Comment by smortex** [comment]
@khaefeli I completely forgot about this until today where I deployed a new site and faced the problem again. I opened #138 to implement the fix properly, thanks!

**Comment by ripienaar** [comment]
Thanks @smortex

**Comment by khaefeli** [comment]
thank you @smortex - I forgot about it too :D
