### ISSUE TITLE
Allow top-level choria::server_config options to be arrays

### ISSUE THREAD

**Issue by snakeb1t** [choria-io/puppet-choria#121]
For example, would be really convenient to be able to do the following:

```
choria::server_config:
  plugin.choria.security.certname_whitelist:
    - 'user1'
    - 'user2'
```

or even more conveniently

```
choria::server_config:
  plugin.choria.security.certname_whitelist: "%{alias('admin_users')}"
```

**Comment by snakeb1t** [comment]
Probably a simple type check needs to be added in https://github.com/choria-io/puppet-choria/blob/master/functions/hash2config.pp , but I suck at ruby. =\

**Comment by ripienaar** [comment]
thank you :)
