### ISSUE TITLE
Allow to configure different logfile / log_level for broker and server

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-choria#130]
The module currently configure both logs for the broker and server with the following 2 parameters:

* `$choria::logfile`
* `$choria::log_level`

In order to ease-up debugging, I would like to configure different values for the two services.  I see 2 ways of reaching my goal:

1. Rename the variables with `broker_` and `server_` prefixes (like the `$(broker|server)_config_file`).  pro: consistent, cons: breaks API;
2. Add these parameters to `choria::broker` and default to the values of the class `choria`.  pro: dos not break API, cons: not that nice.

If we choose to break the API, we can also decide to change the default log filenames to the ones used in the sample configuration files, that is `choria-server.log` and `choria-broker.log`.

What do you think?

**Comment by ripienaar** [comment]
I think we had another ticket for this too so we should probably do something. 

Another option is leave the current options but add also server and broker versions that default to under. If those are set use them else use the current setting?

**Comment by smortex** [comment]
Looks great!  I'll give it a shot tomorrow, thanks!
