### ISSUE TITLE
Modules uploaded to the forge include unneeded files

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-choria#137]
The module uploaded on the puppet forge contains a bunch of useless files, making the module larger than necessary.

The module available at https://forge.puppet.com/v3/files/choria-choria-0.14.0.tar.gz is 1.1 MB. It contains a bunch of files not used by Puppet, including the `.git` directory (that's ~2000 out of 2085 files).  Stripping these unused files, the module shrinks to a few KB.

**Comment by ripienaar** [comment]
first time I built with the pdk packaging rather than puppet one since its not in puppet anymore, no doubt some behavior change, thanks!

**Comment by ripienaar** [comment]
fixed in https://github.com/choria-io/puppet-choria/commit/7e5bbb30d3c6eca1868c3a88702750f82988a118
