### ISSUE TITLE
Add support for Amazon Linux to class choria::repo

### ISSUE THREAD

**Issue by rjd1** [choria-io/puppet-choria#151]
The choria yum repo and rpm packages work just fine on Amazon Linux as it's RHEL compatible. However, the module does not configure the repo properly. 

Current behavior: 
- The original Amazon Linux will get set up with el7
- The newer Amazon Linux 2 will encounter the fail() function on line 12

Desired:
- Original distro gets el6 config ($release = '6')
- Newer version gets el7 ($release = '7')

I'll provide a PR for this.

**Comment by ripienaar** [comment]
thank you :)
