### ISSUE TITLE
Package repositories management is convoluted

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-choria#164]
The `choria::repo` class has a few issues:

1. On Debian, packages are always taken from the "stretch" releases, regardless of the current distro.  However, buster packages are available;
2. Nightly packages configuration only does something on yum repositories, while the project now also provides debian nightly packages (even if they will be dropped in the short term, `choria::nightly_repo` doing nothing on Debian is unexpected);
3. Overall, the code has some duplication.

**Comment by smortex** [comment]
Reworded the issue, now fixing it :-)

**Comment by ripienaar** [comment]
good stuff, thank you
