### ISSUE TITLE
Artifactory requires baseurl and gpg source overrides

### ISSUE THREAD

**Issue by KoenDierckx** [choria-io/puppet-choria#228]
Could a parameter be provided for the base url, but without assuming the /release part needs to be appended (we already need to set this as the remote url in artifactory)
Could this base url also be used for the gpg keys

Currently worked around it with this manifest
  $repo_baseurl = 'https://artifactory.local/artifactory/debian-choria-remote'
  apt::source{"choria-release":
    ensure        => 'present',
    notify_update => true,
    comment       => "Choria Orchestrator Releases",
    location      => "${repo_baseurl}/ubuntu",
    release       => $facts["os"]["distro"]["codename"],
    repos         => "main",
    key           => {
      id     => "5921BC1D903D6E0353C985BB9F89253B1E83EA92",
      source => "${repo_baseurl}/gpgkey"
    },
  }
  class { 'choria':
    manage_package_repo => false,
  }

**Comment by ripienaar** [comment]
Yeah current base url probably is not done in the best way possible, it would though be an annoying breaking change but probably worth doing.

**Comment by ripienaar** [comment]
Do you want to send a PR that updates this? Just change it so default base_url includes the /release etc stuff up to the repo name

**Comment by ripienaar** [comment]
Closing this, we are moving away from allowing repos to be customised, you can now just turn it off and make your own yumrepo.

Supporting all possible permutations of peoples setups is just too much weirdness, and those with own repos are likely already familiat with `yumrepo`
