### ISSUE TITLE
Allow the module to configure choria leaf nodes

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-choria#238]
### Description of the problem

In a setup with high latency / unreliable network, communicating with the middleware can be troublesome:

```sh-session
romain@zappy ~ % choria ping
[...]
---- ping statistics ----
47 replies max: 385.029 min: 173.725 avg: 239.244 overhead: 900.123
```

Nats allows configuring _leafnodes_ which acts as a gateway and maintains an open connection to the main message broker.  The client can then be configured to communicate with the leafnode instead of the main broker, reducing the time needed to establish connections and improving the overall reliability:

```sh-session
romain@zappy ~ % choria ping
[...]
---- ping statistics ----
47 replies max: 514.952 min: 174.940 avg: 324.016 overhead: 57.877
```

### Solution

Configuration has to happen in 3 different places:

1. On the message broken, the `leafnode_port` must be set:

```
plugin.choria.network.leafnode_port = 7422
```

2. On a node near the client (or the client itself), a broker must be started with this configuration:

```
plugin.choria.broker_network = true
plugin.choria.network.leafnode_remotes = central
plugin.choria.network.leafnode_remote.central.url = leaf://hostname.of.the.message.broker:7422
```

3. On the client:
```
plugin.choria.middleware_hosts = hostname.of.the.leafnode:4222
```

### What needs to be done

Allowing to configure the above settings through the module would be awesome

**Comment by ripienaar** [comment]
So we'd need to define some types like

```
type Choria::Leafnodes = Hash[String, Choria::Leafnode]
```

and Leafnode has keys `account`, `credentials`, `url`, `tls_cert`, `tls_key`, `tls_ca`, `tls_verify` and `tls_disable`

Then we walk them similar to this:

https://github.com/choria-io/puppet-choria/blob/020d0374d0c0fbc5fafc64016159c548dc5601c2/templates/broker.cfg.epp#L82-L100

**Comment by ripienaar** [comment]
```type Choria::Leafnode = Struct[{
  "url"         => String,
  "account"     => Optional[String],
  "credentials" => Optional[Variant[Stdlib::Compat::Absolute_path, String[0, 0]]],
  "tls_cert"    => Optional[Variant[Stdlib::Compat::Absolute_path, String[0, 0]]],
  "tls_key"     => Optional[Variant[Stdlib::Compat::Absolute_path, String[0, 0]]],
  "tls_ca"      => Optional[Variant[Stdlib::Compat::Absolute_path, String[0, 0]]],
  "tls_verify"  => Optional[Boolean],
  "tls_disable" => Optional[Boolean],
}]```

**Comment by ripienaar** [comment]
@smortex PR up, I'd love a blog post describing this :)

**Comment by smortex** [comment]
> @smortex PR up, I'd love a blog post describing this :)

It's WIP…  I would like to add diagrams, what did you used to make them?

**Comment by ripienaar** [comment]
draw.io you can take any of the existing png diagrams on choria.ok and load them up there and get vector drawings from tbe png
