### ISSUE TITLE
Support for el6 dropped on 0.23.0

### ISSUE THREAD

**Issue by pebtron** [choria-io/puppet-choria#245]
With the release of 0.23.0, data/os/RedHat.yaml was updated to ensure RPM package version 0.21.0 is installed. However as of this release, there is no 0.21.0 RPM for el6 available on [https://packagecloud.io/choria/release](url). Is support for el6 removed on purpose or is this an oversight? There was no mention of this in the Changelog.

**Comment by ripienaar** [comment]
Yes, el6 is not supported anymore I am afraid.

This is mentioned in the changelog, the release notes and the blog post announcing the release.

EL6 is past end of life, golang also does not support el6 kernels anymore, afraid its the end of the line.

**Comment by pebtron** [comment]
Ok thanks.
-Paul
