### ISSUE TITLE
Support new repos

### ISSUE THREAD

**Issue by ripienaar** [choria-io/puppet-choria#271]

**Comment by pebtron** [comment]
While http://mirrorlists.choria.io/yum/release/el/7/x86_64.txt exists, http://mirrorlists.choria.io/yum/release/el/7Server/x86_64.txt does not.

**Comment by ripienaar** [comment]
@pebtron hmm, what os do you use that sets that particular combination? 

Should be there now anyway

**Comment by ripienaar** [comment]
Weird, mine didnt, anyway sorted now :)
