### ISSUE TITLE
choria::broker::stats_listen_address default doesn't work without IPv6

### ISSUE THREAD

**Issue by silug** [choria-io/puppet-choria#298]
After upgrading, the broker wouldn't start on my puppetserver that has IPv6 disabled.  Since the `choria-broker` service was set to auto-restart, `systemctl` wasn't reporting an obvious error, so `puppet` wasn't giving me an error either.

Setting the following fixed the issue for me:
```
choria::broker::stats_listen_address: '127.0.0.1'
choria::broker::listen_address: '0.0.0.0'
```

Presumably this is related to https://github.com/choria-io/puppet-choria/commit/32b8bf46dc20b42b4cde4148e5c8ca148d53a01b.  Perhaps using `localhost` instead of `::1` for the default would work?

**Comment by smortex** [comment]
In an ideal world, the service should listen on both `::1` and the legacy `127.0.0.1`.  Setting `choria::broker::stats_listen_address` to localhost currently only binds to only one of these addresses.  I am looking if/how we can improve this.
