### ISSUE TITLE
After installing Choria on Windows VM initally the VM does not show in choria ping -A puppet

### ISSUE THREAD

**Issue by wernerbahlke** [choria-io/puppet-choria#305]
I wrote my own Windows installer base on what @smortex had send me.

I also wrote a windows_service.pp to start up the service but maybe that is done to early.

Anyways after a successful install I do not see the VM in the list of choria ping -A puppet.

But when I stop and start the choria-server on the VM I see it and  can can run successfully mco puppet runonce -F hostname=<windows host>.

**Comment by wernerbahlke** [comment]
As a workaround I added a subscribe to my the service command in windows_service.pp and subscribed to the last file installed by mcollective_util_actionplicy. This worked and I can then run mco puppet runonce against the Windows VM.

**Comment by ripienaar** [comment]
You should probably do something like:

```
Mcollective::Module_plugin<| |> ~> Service["choria"]
```

This will subscribe service `choria` (replace with windows service name) to all plugin related files

**Comment by ripienaar** [comment]
I will close this, there's nothing I can do to fix this - your service class need to subscribe to the right things thats about it.
