### ISSUE TITLE
Support the architecture for Debian repositories

### ISSUE THREAD

**Issue by dploeger** [choria-io/puppet-choria#331]
Debian repositories on multi-arch systems issue the following warning if the package source doesn't support all architectures:

```
N: Skipping acquire of configured file 'jammy/binary-i386/Packages' as repository 'mirror://mirrorlists.choria.io/apt/release/ubuntu/jammy/mirrors.txt ubuntu InRelease' doesn't support architecture 'i386'
```

To circumvent that, the choria repo should include the "archicture" parameter set to the system architecture.

I'll add a PR to issue that.

**Comment by ripienaar** [comment]
Thank you @dploeger

**Comment by dploeger** [comment]
@ripienaar Do you know when this will be released on the forge?

**Comment by ripienaar** [comment]
Unfortunately I did a release like just before you opened your PR, but I will let that release sit a day or 2 and do another with this in it.
