### ISSUE TITLE
add 'name' option to yum repositories

### ISSUE THREAD

**Issue by vchepkov** [choria-io/puppet-choria#36]
without 'name' option yum emits warning messages:

```
# yum check-update
Loaded plugins: fastestmirror
Repository 'choria_release' is missing name in configuration, using id

```

**Comment by ripienaar** [comment]
thanks a lot :)

re that other thing with puppet not being in the path, I fixed it, if you wanted to continue testing do `ln -s /opt/puppetlabs/bin/puppet /usr/bin/puppet` and that should sort it out till the next release of the choria daemon

**Comment by vchepkov** [comment]
I was testing shell agent and noticed deprecation in nats module, so decided to check them out.
I can wait for official releases for both choria/nats (removing bits) and choria/choria (with broker)
I was testing from the 'masters' on both

Thanks for fixing agent_shell too, It works now!

**Comment by ripienaar** [comment]
OK :) yeah right now many things are in flux if you run from the repos, release should be ~2ish weeks
