### ISSUE TITLE
add support for FreeBSD

### ISSUE THREAD

**Issue by smortex** [choria-io/puppet-choria#47]
The current code needs some minor adjustments to configure choria on FreeBSD (choria is not yet shipped in the official FreeBSD ports tree, but is available from the [puppet@ WIP repo](https://github.com/smortex/puppet5)):

* FreeBSD does not have a `root` group, the `wheel` group can be used instead;
* Configuration files of choria are stored in `/usr/local/etc/choria`.

Configuring these settings with hiera should make sense.  Maybe it's worth moving all init.pp's default values to hiera as it's done in various modules?

**Comment by ripienaar** [comment]
yup, all for making this have data like that others :)
