### ISSUE TITLE
Module fails on Ubuntu with facter 2.5

### ISSUE THREAD

**Issue by bastelfreak** [choria-io/puppet-choria#73]
https://github.com/choria-io/puppet-choria/blob/755b017a7d93b61d46a097bb52af1f89d0527e58/manifests/repo.pp#L38

this fact isn't available on facter 2.5, it got introduced later. 2.5 is still pretty common, I think it would be nice if this module would be still compatible with the older facter version.

**Comment by ripienaar** [comment]
thanks @bastelfreak 

what ubuntu has this version?

**Comment by bastelfreak** [comment]
I lost track on which operating system ships which facter version / which version is bundled within the AIO packages. Currently facter 2.5 is the last version that was shipped as a gem, so that is used within 99% of the rspec-puppet tests. We get the mocked data from https://github.com/camptocamp/facterdb/tree/master/facts/2.5. This issue is finally gone fater cfacter 3.X will get released within the facter namespace on rubygems: https://tickets.puppetlabs.com/browse/FACT-1542

**Comment by ripienaar** [comment]
@bastelfreak oh yeah rspec ugh, I tend to always just provide stub facts but yeah its a pain in the arse
