### ISSUE TITLE
Bad class in config.pp #31 (fix inside)

### ISSUE THREAD

**Issue by ds2000** [choria-io/puppet-choria#88]
Hi all,
Very quick one, I'd have fixed myself but I can't couldn't create a branch.

Line 31 of config.pp reads:
   `content => mcollective::hash2config($config),`

It should read:
   ` content => choria::hash2config($config),`

Thanks

Dave

**Comment by ripienaar** [comment]
nice, i wonder how this did not bite us before? Looks like `mcollective::hash2config` does exist so it should work, did you have a failure? 

Obviously using the one here is best so we'll fix that, thanks!

**Comment by ds2000** [comment]
Yes I did, we don't currently have mcollective on site so I guess maybe an old class was possibly picked up with you guys?
Onto the next step for me, thanks

**Comment by ripienaar** [comment]
this module requires the mcollective one, choria installs mcollective, so not clear how you got here :)

https://github.com/choria-io/puppet-choria/blob/f3f5e1323c7a3c8c68428ca39888520eb2d4a171/metadata.json#L14

**Comment by ds2000** [comment]
I've just double checked out config, it appears someone may have installed
mcollective |2017/03/28|     |Release 0.0.26 in our puppet module
directory.  However, that version doesn't have a functions subfolder :) -
looking deeper it looks like someone has tried and failed to install an old
Choria as well.

I'll clean it all down and start again, just in case.

Thanks
Dave
