### ISSUE TITLE
systemctl cannot start broker service, starts OK manually

### ISSUE THREAD

**Issue by ds2000** [choria-io/puppet-choria#89]
Hi (again) ;)

I'm trying to get the default broker up and running on a standalone node (vanilla box managed by puppet).
The service has the following control file:

```
/usr/lib/systemd/system/choria-broker.service
[Unit]
Description=The Choria Orchestrator Middleware Broker
After=network.target

[Service]
StandardOutput=syslog
StandardError=syslog
User=root
Group=root
ExecStart=/usr/sbin/choria broker --config=/etc/choria/broker.conf

[Install]
WantedBy=multi-user.target
```

However, when the system attempts to start the service, the log reports:

```
{"level":"fatal","msg":"Could not configure Choria: Could not initialize Choria: SSL setup is not valid, 1 errors encountered: SSL Directory does not exist: exec: \"puppet\": executable file not found in $PATH","time":"2018-08-16T14:29:18+02:00"}
```

Running:
```
/usr/sbin/choria broker --config=/etc/choria/broker.conf
```
The service starts correctly.
OS is Red Hat Enterprise Linux Server release 7.4 (Maipo)

selinux and other nasty services are disabled.  It looks as though somewhere the $PATH isn't getting picked up.  I'll keep looking and report back if / when I find a fix.  Any suggestions welcome too.

Thanks

**Comment by ripienaar** [comment]
are you using the default puppet-agent rpm?

**Comment by ds2000** [comment]
Quite possibly, I've inherited a prebuilt env, we're running open source.

```
yum list puppet-agent
Loaded plugins: search-disabled-repos, versionlock
puppet-agent.x86_64                     5.3.3-1.el7                   @puppet5
```

**Comment by ds2000** [comment]
I should expand on that, we have pre-built AMI's from our security team that we apply our own config to.

**Comment by ripienaar** [comment]
and your choria rpm version?

**Comment by ds2000** [comment]
Doh!  I blindly copied the:
choria::version: 0.0.7-1.el%{facts.os.release.major}

From the front page, my apologies, and thanks for the quick reply.  Back in my box

**Comment by ripienaar** [comment]
no worries :)

**Comment by ripienaar** [comment]
Closing, feel free to reopen if you still have issues
