### ISSUE TITLE
"accept4: too many open files" in /var/log/choria.log

### ISSUE THREAD

**Issue by wiad** [choria-io/puppet-choria#91]
Systemd's default setting for open file handles is potentially too low for Choria network broker. On my system (RHEL7) it is 1024, which in time renders the following error in /var/log/choria.log:

```
{"component":"network_broker","level":"error","msg":"Temporary Client Accept Error (accept tcp [::]:61614: accept4: too many open files), sleeping 10ms","time":"2018-09-11T06:03:22Z"}
{"component":"network_broker","level":"error","msg":"Temporary Client Accept Error (accept tcp [::]:61614: accept4: too many open files), sleeping 20ms","time":"2018-09-11T06:03:22Z"}
{"component":"network_broker","level":"error","msg":"Temporary Client Accept Error (accept tcp [::]:61614: accept4: too many open files), sleeping 40ms","time":"2018-09-11T06:03:22Z"}
```

The `puppet-nats` module has a `limit_nofile` parameter just for this reason which sets the `LimitNOFILE` parameter in the systemd unit file, but the Choria module seems to be missing this. It would be nice to have it added.

**Comment by ripienaar** [comment]
Fixed in https://github.com/choria-io/go-choria/issues/444
